# yaml-language-server: $schema=https://raw.githubusercontent.com/Second-Hand-Friends/kleinanzeigen-bot/main/schemas/config.schema.json
login:
  username: "aymenrizwandesign@gmail.com"
  password: "Press@911"

ad_files:
  - "./ads/**/*.yaml"

ad_defaults:
  type: OFFER
  price_type: NEGOTIABLE
  shipping_type: PICKUP
  republication_interval: 7

browser:
  use_private_window: false
